### ISSUE TITLE
Reporting doc-test failures is misleading

### ISSUE THREAD

**Issue by gdhgdhgdh** [JetBrains/teamcity-rust-plugin#34]
When running `cargo test --all` manually, I had failing doc-tests e.g.

```
    Doc-tests netopt
error[E0465]: multiple rlib candidates for `quick_error` found
  --> /opt/teamcityagent/work/485272bd58bfc4f7/poltergeist/src/netopt/src/lib.rs:10:1
   |
10 | extern crate quick_error;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: candidate #1: /opt/teamcityagent/work/485272bd58bfc4f7/poltergeist/target/release/deps/libquick_error-ad4e7dd1aa51c0e7.rlib
  --> /opt/teamcityagent/work/485272bd58bfc4f7/poltergeist/src/netopt/src/lib.rs:10:1
   |
10 | extern crate quick_error;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^
note: candidate #2: /opt/teamcityagent/work/485272bd58bfc4f7/poltergeist/target/release/deps/libquick_error-c03e0e7650d0e89d.rlib
  --> /opt/teamcityagent/work/485272bd58bfc4f7/poltergeist/src/netopt/src/lib.rs:10:1
   |
10 | extern crate quick_error;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0463]: can't find crate for `quick_error`
  --> /opt/teamcityagent/work/485272bd58bfc4f7/poltergeist/src/netopt/src/lib.rs:10:1
   |
10 | extern crate quick_error;
   | ^^^^^^^^^^^^^^^^^^^^^^^^^ can't find crate

error: aborting due to 2 previous errors
```

However when the TC runner in `test` mode with `--all` option runs this step, the log output is dozens of lines of 

```
[Step 6/8] Internal error occurred. See agent log for details.
[Step 6/8] Internal error occurred. See agent log for details.
[Step 6/8] Internal error occurred. See agent log for details.
[Step 6/8] Internal error occurred. See agent log for details.
[...]
```

and then a huge stacktrace which starts 

```
[Step 6/8] error: aborting due to 2 previous errorsthread '<unnamed>' panicked at 'Box<Any>', /checkout/src/librustc_errors/lib.rs:454
stack backtrace:
1:     0x7f1e7efb4c59 - std::sys::imp::backtrace::tracing::imp::write::hbb14611794d3841b
at /checkout/src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:42
2:     0x7f1e7efc32fe - std::panicking::default_hook::{{closure}}::h6ed906c7818ac88c
at /checkout/src/libstd/panicking.rs:351
[...]
```

The errors have now been resolved by running manually on the agent, but this rather misses the point of a CI system ;)

**Comment by dtretyakov** [comment]
@gdhgdhgdh, thanks for reporting this issue, it will be fixed soon.

**Comment by dtretyakov** [comment]
@gdhgdhgdh, you can download rust plugin build with a fix:
https://plugins.jetbrains.com/plugin/9044-rust-and-cargo
