### ISSUE TITLE
Exception in agent logs if no tools installed on agent

### ISSUE THREAD

**Issue by VladRassokhin** [JetBrains/teamcity-rust-plugin#73]
```text
[2024-12-11 12:08:03,427]   WARN - ildServer.util.EventDispatcher - Error in event handler: Error calling method AgentLifeCycleListener.beforeAgentConfigurationLoaded for listener jetbrains.buildServer.rust.CargoToolProvider: java.util.NoSuchElementException
[2024-12-11 12:08:03,427]  DEBUG - ildServer.util.EventDispatcher - Error in event handler
Error calling method AgentLifeCycleListener.beforeAgentConfigurationLoaded for listener jetbrains.buildServer.rust.CargoToolProvider: java.util.NoSuchElementException
	at jetbrains.buildServer.util.EventDispatcher.invokeListeners(EventDispatcher.java:175)
	at jetbrains.buildServer.util.EventDispatcher.lambda$dispatch$0(EventDispatcher.java:134)
	at jetbrains.buildServer.util.NamedThreadFactory.executeWithNewThreadName(NamedThreadFactory.java:76)
	at jetbrains.buildServer.util.EventDispatcher.dispatch(EventDispatcher.java:134)
	at jetbrains.buildServer.util.EventDispatcher$2.invoke(EventDispatcher.java:82)
	at com.sun.proxy.$Proxy28.beforeAgentConfigurationLoaded(Unknown Source)
	at jetbrains.buildServer.agent.impl.BuildAgentImpl.init(BuildAgentImpl.java:896)
	at jetbrains.buildServer.agent.AgentMain2.startAgent(AgentMain2.java:222)
	at jetbrains.buildServer.agent.AgentMain2.main2(AgentMain2.java:98)
	at jetbrains.buildServer.agent.AgentMain2.main(AgentMain2.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jetbrains.buildServer.agent.AgentMain.main(AgentMain.java:44)
Caused by: java.util.NoSuchElementException
	at jetbrains.buildServer.rust.AbstractToolProvider.findToolPath(AbstractToolProvider.kt:148)
	at jetbrains.buildServer.rust.AbstractToolProvider.beforeAgentConfigurationLoaded(AbstractToolProvider.kt:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at jetbrains.buildServer.util.EventDispatcher.invokeListeners(EventDispatcher.java:157)
	... 14 more
```

**Comment by VladRassokhin** [comment]
Same for RustcToolProvider and RustupToolProvider
